[package]
name = "candor"
version = "0.4.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
can-dbc = "6.0.0"
socketcan = { version = "3.3.0", optional = true }

[features]
socketcan = ["dep:socketcan"]
